version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    #expose:
    #  - "9092"
    environment:
    #  KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    #  KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
    #  KAFKA_ADVERTISED_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
    #  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
    #  KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    #   KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    #   KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
       KAFKA_ADVERTISED_HOST_NAME: localhost
       KAFKA_ADVERTISED_PORT: "9092"
      #    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
       KAFKA_CREATE_TOPICS: "users:1:1"
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  #app:
  #  build:
   #   context: .
   #   dockerfile: Dockerfile
   # links:
   #   - kafka


#version: '3'
#services:
#  zookeeper:
#    image: wurstmeister/zookeeper
#  kafka:
#    image: wurstmeister/kafka
#    links:
#      - zookeeper
#    environment:
#      KAFKA_ADVERTISED_LISTENERS: 127.0.0.1
#      KAFKA_ADVERTISED_PORT: 9092
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    links:
#      - kafka

